services:
  # Service Web de l'application GESCOM
  - type: web
    name: gescom-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon # ou votre région préférée
    plan: starter # ou free pour commencer
    
    # Variables d'environnement
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Dspring.profiles.active=render"
      - key: DATABASE_URL
        fromDatabase:
          name: gescom-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: gescom-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gescom-db
          property: password
    
    # Configuration du build
    buildCommand: ""  # Le Dockerfile gère le build
    startCommand: ""  # Le Dockerfile gère le start
    
    # Health check
    healthCheckPath: /actuator/health
    
    # Configuration du port
    # Render définit automatiquement la variable PORT

# Base de données PostgreSQL (déjà créée selon vos informations)
databases:
  - name: gescom-db
    databaseName: gescom_k7fn
    user: gescom_k7fn_user
    region: oregon
    plan: free # ou starter selon vos besoins